---
version: '2.2'
services:
  pytest:
    image: registry.klautspeicher.de/pytest:0.1
    container_name: pytest
    build:
      context: ./
      dockerfile: Dockerfile-pytest
      args:
        LIB_RD_KAFKA_VERSION: 1.0.0
    # command: pyb install_dependencies run_unit_tests
    command: pyb run_unit_tests
    volumes:
      - ../:/app
    networks:
      - esnet

networks:
  esnet:
